server:
  port: 9091
  
spring:
  profiles:
    active: dev
    
  application:
    name: FOOD-CATALOGUE-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql